"""Initial schema with users, oauth_tokens, sleep, recovery, workout, cycle, and sync_status tables

Revision ID: f00956217044
Revises: 
Create Date: 2025-12-18 10:08:20.031172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f00956217044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whoop_user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_whoop_user_id'), 'users', ['whoop_user_id'], unique=True)
    op.create_table('cycle_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone_offset', sa.String(length=10), nullable=True),
    sa.Column('strain_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kilojoules', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_records_score_state'), 'cycle_records', ['score_state'], unique=False)
    op.create_index(op.f('ix_cycle_records_start_time'), 'cycle_records', ['start_time'], unique=False)
    op.create_index(op.f('ix_cycle_records_user_id'), 'cycle_records', ['user_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_expires_at'), 'oauth_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_table('recovery_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('created_at_whoop', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovery_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('hrv_rmssd', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('spo2_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skin_temp_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('calibrating', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_records_created_at_whoop'), 'recovery_records', ['created_at_whoop'], unique=False)
    op.create_index(op.f('ix_recovery_records_cycle_id'), 'recovery_records', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_recovery_records_user_id'), 'recovery_records', ['user_id'], unique=False)
    op.create_table('sleep_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone_offset', sa.String(length=10), nullable=True),
    sa.Column('light_sleep_duration', sa.Integer(), nullable=True),
    sa.Column('slow_wave_sleep_duration', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_duration', sa.Integer(), nullable=True),
    sa.Column('awake_duration', sa.Integer(), nullable=True),
    sa.Column('sleep_performance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sleep_consistency_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('respiratory_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sleep_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('is_nap', sa.Boolean(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_records_end_time'), 'sleep_records', ['end_time'], unique=False)
    op.create_index(op.f('ix_sleep_records_score_state'), 'sleep_records', ['score_state'], unique=False)
    op.create_index(op.f('ix_sleep_records_start_time'), 'sleep_records', ['start_time'], unique=False)
    op.create_index(op.f('ix_sleep_records_user_id'), 'sleep_records', ['user_id'], unique=False)
    op.create_table('sync_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_record_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_status_data_type'), 'sync_status', ['data_type'], unique=False)
    op.create_index(op.f('ix_sync_status_user_id'), 'sync_status', ['user_id'], unique=False)
    op.create_table('workout_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone_offset', sa.String(length=10), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('sport_name', sa.String(length=100), nullable=True),
    sa.Column('strain_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('kilojoules', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altitude_gain_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('altitude_change_meters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zone_zero_duration', sa.Integer(), nullable=True),
    sa.Column('zone_one_duration', sa.Integer(), nullable=True),
    sa.Column('zone_two_duration', sa.Integer(), nullable=True),
    sa.Column('zone_three_duration', sa.Integer(), nullable=True),
    sa.Column('zone_four_duration', sa.Integer(), nullable=True),
    sa.Column('zone_five_duration', sa.Integer(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_records_score_state'), 'workout_records', ['score_state'], unique=False)
    op.create_index(op.f('ix_workout_records_sport_id'), 'workout_records', ['sport_id'], unique=False)
    op.create_index(op.f('ix_workout_records_start_time'), 'workout_records', ['start_time'], unique=False)
    op.create_index(op.f('ix_workout_records_user_id'), 'workout_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_records_user_id'), table_name='workout_records')
    op.drop_index(op.f('ix_workout_records_start_time'), table_name='workout_records')
    op.drop_index(op.f('ix_workout_records_sport_id'), table_name='workout_records')
    op.drop_index(op.f('ix_workout_records_score_state'), table_name='workout_records')
    op.drop_table('workout_records')
    op.drop_index(op.f('ix_sync_status_user_id'), table_name='sync_status')
    op.drop_index(op.f('ix_sync_status_data_type'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_sleep_records_user_id'), table_name='sleep_records')
    op.drop_index(op.f('ix_sleep_records_start_time'), table_name='sleep_records')
    op.drop_index(op.f('ix_sleep_records_score_state'), table_name='sleep_records')
    op.drop_index(op.f('ix_sleep_records_end_time'), table_name='sleep_records')
    op.drop_table('sleep_records')
    op.drop_index(op.f('ix_recovery_records_user_id'), table_name='recovery_records')
    op.drop_index(op.f('ix_recovery_records_cycle_id'), table_name='recovery_records')
    op.drop_index(op.f('ix_recovery_records_created_at_whoop'), table_name='recovery_records')
    op.drop_table('recovery_records')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_expires_at'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_cycle_records_user_id'), table_name='cycle_records')
    op.drop_index(op.f('ix_cycle_records_start_time'), table_name='cycle_records')
    op.drop_index(op.f('ix_cycle_records_score_state'), table_name='cycle_records')
    op.drop_table('cycle_records')
    op.drop_index(op.f('ix_users_whoop_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
